#' Class check
#' @param x object
#' @return logical
#' @export
is.hcai_predicted_df <- function(x) "hcai_predicted_df" %in% class(x)

# print method for predicted data frame
#' @export
print.hcai_predicted_df <- function(x, ...) {
  x <- change_pr_metric(x)
  mi <- attr(x, "model_info")
  mes <- paste0("healthcareai-predicted data. Column \"predicted_",
                mi$target, "\" predicted by ",
                mi$algorithm, " tuned on ", mi$metric,
                ". Performance in training: ", mi$metric, " = ",
                round(mi$performance, 2), ".\n")
  message(mes)
  # Avoid dispatching print.hcai_prepped_df:
  y <- structure(x, class = class(x)[!stringr::str_detect(class(x), "^hcai")])
  print(y)
  return(invisible(x))
}

#' Summary method for predicted data frame
#' @export
#' @param d data frame from `predict.model_list`
#' @return list of model info
#' @noRd
summary.hcai_predicted_df <- function(object, ...) {
  mi <- attr(object, "model_info")
  mes <- paste0("predicted_", mi$target, " generated by ", mi$algorithm
                , ". Training performance (out-of-fold) was ", mi$metric,
                " = ", round(mi$performance, 3)
  )
  message(mes)
  print(object)
  return(invisible(mi))
}

