#########################################
### S3 generics for hcai_predicted_df ###
#########################################

#' Class check
#' @param x object
#' @return logical
#' @export
is.hcai_predicted_df <- function(x) "hcai_predicted_df" %in% class(x)

# print method for predicted data frame
#' @export
print.hcai_predicted_df <- function(x, ...) {
  x <- change_pr_metric(x)
  mi <- attr(x, "model_info")
  mes <- paste0("healthcareai-predicted data. Column \"predicted_",
                mi$target, "\" predicted by ",
                mi$algorithm, " tuned on ", mi$metric,
                ". Performance in training: ", mi$metric, " = ",
                round(mi$performance, 2), ".\n")
  message(mes)
  # Avoid dispatching print.hcai_prepped_df:
  y <- structure(x, class = class(x)[!stringr::str_detect(class(x), "^hcai")])
  print(y)
  return(invisible(x))
}

#' Summary method for predicted data frame
#' @export
#' @param d data frame from `predict.model_list`
#' @return list of model info
#' @noRd
summary.hcai_predicted_df <- function(object, ...) {
  mi <- attr(object, "model_info")
  mes <- paste0("predicted_", mi$target, " generated by ", mi$algorithm
                , ". Training performance (out-of-fold) was ", mi$metric,
                " = ", round(mi$performance, 3)
  )
  message(mes)
  print(object)
  return(invisible(mi))
}

################################################
### Utility functions for predict.model_list ###
################################################

#' Determine whether to prep_data before making predictions
#' @noRd
determine_prep <- function(object, newdata, mi = extract_model_info(object)) {
  # If there's a recipe, it looks like prep is needed
  needs_prep <- "recipe" %in% names(attributes(object))
  # If newdata has prepped signature, then prepping definitely isn't needed
  been_prepped <- inherits(newdata, "hcai_prepped_df")
  if (!needs_prep || been_prepped)  {
    return(FALSE)
  } else {
    # If data was prepped in training and newdata doesn't appear to have been prepped,
    # then we will prep, but check to see if it looks like newdata has already been
    # and issue a warning if so
    if (dfs_compatible(dplyr::select(object[[1]]$trainingData, -.outcome),
                       dplyr::select(newdata, -which(names(newdata) == mi$target))))
      warning("The data used in model training was prepped using `prep_data`. ",
              "Therefore, the data you want to make predictions on must also be prepped. ",
              "It looks like you might have done that by passing `newdata` ",
              "through `prep_data` before passing it to `predict`, but I can't be sure, ",
              "so it will be prepped now before making predictions. ",
              "If you passed the prediction data through `prep_data` before ",
              "`predict`, set `predict(prepdata = FALSE)`.")
    return(TRUE)
  }
}

#' When not prepping in predict, check that prediction will work
#' @noRd
ready_no_prep <- function(training_data, newdata) {
  # Select variables to be used in prediction:
  training_data <- dplyr::select(training_data, -.outcome)
  to_pred <- newdata[, names(newdata) %in% names(training_data), drop = FALSE]
  # Check for no missingness
  has_missing <- missingness(to_pred, FALSE) > 0
  if (any(has_missing))
    stop("The following variables have missingness that needs to be ",
         "addressed before making predictions. ",
         "Consider using prep_data to address this.\n\t",
         paste(names(has_missing)[has_missing], collapse = ", "))
  # Check for no new levels in factors
  missing_levels <-
    find_new_levels(to_pred, training_data) %>%
    format_new_levels()
  if (length(missing_levels))
    stop("The following variable(s) had the following value(s) ",
         "in predict that were not observed in training. ",
         "Consider using prep_data to address this.", missing_levels)
  return(to_pred)
}

#' check for new factor levels and send new data to prep_data before predicting
#' @noRd
ready_with_prep <- function(object, newdata, mi = extract_model_info(object)) {
  recipe <- attr(object, "recipe")
  if (is.null(recipe))
    stop("Can't prep data in prediction without a recipe from training data.")

  # Check for new levels in factors not present in training and warn if present
  new_levels <- find_new_levels(newdata, attr(recipe, "factor_levels"))
  # Don't check ignored columns. NAs are checked in prep_data
  new_levels <- new_levels[!names(new_levels) %in% attr(recipe, "ignored_columns")] %>%
    format_new_levels(remove_nas = TRUE)
  if (length(new_levels))
    warning("The following variables(s) had the following value(s) in ",
            "predict that were not observed in training. ",
            new_levels)
  prep_data(newdata, recipe = recipe) %>%
    return()
}
